# Generated by Django 5.1.2 on 2024-10-24 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('albume_title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('albume_logo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=100)),
                ('song_title', models.CharField(max_length=255)),
                ('albume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.albume')),
            ],
        ),
    ]
